# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swift-sestek-webchat-example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'sestek-webchat-ios', :path => '../../'

  # Pods for swift-sestek-webchat-example

  target 'swift-sestek-webchat-exampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swift-sestek-webchat-exampleUITests' do
    # Pods for testing
  end

end
