# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

def app_pods
  pod 'IQKeyboardManagerSwift'
  pod 'Down'
  pod 'Alamofire', '~> 4.9.1'
end

target 'swift-sestek-webchat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift-sestek-webchat
  app_pods

  target 'swift-sestek-webchatTests' do
    # Pods for testing
  end

end
